### PR TITLE
Updater bug Spotted

### PR DESCRIPTION
**Pull request by StarkGang**

### CODE REVIEW

**Comment by pureindialover** [comment]
u gay af

**Comment by StarkGang** [comment]
@pureindialover What Do You Mean? Do i know You?

**Comment by pureindialover** [comment]
@StarkGang ja na lode yanhi patak ke chod dunga

**Comment by StarkGang** [comment]
> @StarkGang ja na lode yanhi patak ke chod dunga
English, Only.

**Comment by pureindialover** [comment]
> 
> 
> > @StarkGang ja na lode yanhi patak ke chod dunga
> > English, Only.

yes leme translate for u
i will toss u off the ground and fuck u there only

**Comment by xditya** [comment]
not a bug.

**Comment by sppidy** [comment]
Lel what a nice bug 😂😂

**Pull request closed without merging**
